# -*- coding: utf-8 -*-
import datetime

INDUSTRY = {
    '1': '農業，林業',
    '2': '漁業',
    '3': '鉱業，採石業，砂利採取業',
    '4': '建設業',
    '5': '製造業',
    '6': '電気・ガス・熱供給・水道業',
    '7': '情報通信業',
    '8': '運輸業，郵便業',
    '9': '卸売業・小売業',
    '10': '金融業・保険業',
    '11': '不動産業，物品賃貸業',
    '12': '学術研究，専門・技術サービス業',
    '13': '宿泊業，飲食サービス業',
    '14': '生活関連サービス業，娯楽業',
    '15': '教育，学習支援業',
    '16': '医療，福祉',
    '17': '複合サービス事業',
    '18': 'サービス業（他に分類されないもの）',
    '19': '公務（他に分類されるものを除く）',
    '20': '分類不能の産業'
}

YEAR_LIST = sorted(list(range(1940, 2010)), reverse=True)
YEAR_EXPIRATION_LIST = [
    datetime.date.today().year,
    datetime.date.today().year + 1,
    datetime.date.today().year + 2,
    datetime.date.today().year + 3,
    datetime.date.today().year + 4,
    datetime.date.today().year + 5,
]
MONTH_LIST = list(range(1, 13))
DAY_LIST   = list(range(1, 32))
JAPANESE_LIST = ['N1', 'N2', 'N3', 'N4', 'N5', 'None']
NATIONALITY_LIST = [
    'Bhutan',
    'Brunei Darussalam',
    'Cambodia',
    'China',
    'India',
    'Indonesia',
    'Japan',
    "Lao People's Democratic Republic",
    'Malaysia',
    'Mongolia',
    'Myanmar',
    'Nepal',
    'Philippines',
    'Singapore',
    'Sri Lanka',
    'Taiwan, Province of China',
    'Thailand',
    'Viet Nam',
    'Korea, Republic of',
    'Other',
]
PREFECTURES = {
    '1': '北海道 hokkaido',
    '2': '青森県 aomori',
    '3': '岩手県 iwate',
    '4': '宮城県 miyagi',
    '5': '秋田県 akita',
    '6': '山形県 yamagata',
    '7': '福島県 fukushima',
    '8': '茨城県 ibaraki',
    '9': '栃木県 tochigi',
    '10': '群馬県 gunma',
    '11': '埼玉県 saitama',
    '12': '千葉県 chiba',
    '13': '東京都 tokyo',
    '14': '神奈川県 kanagawa',
    '15': '新潟県 niigata',
    '16': '富山県 toyama',
    '17': '石川県 ishikawa',
    '18': '福井県 fukui',
    '19': '山梨県 yamanashi',
    '20': '長野県 nagano',
    '21': '岐阜県 gifu',
    '22': '静岡県 shizuoka',
    '23': '愛知県 aichi',
    '24': '三重県 mie',
    '25': '滋賀県 shiga',
    '26': '京都府 kyoto',
    '27': '大阪府 osaka',
    '28': '兵庫県 hyogo',
    '29': '奈良県 nara',
    '30': '和歌山県 wakayama',
    '31': '鳥取県 tottori',
    '32': '島根県 shimane',
    '33': '岡山県 okayama',
    '34': '広島県 hiroshima',
    '35': '山口県 yamaguchi',
    '36': '徳島県 tokushima',
    '37': '香川県 kagawa',
    '38': '愛媛県 ehime',
    '39': '高知県 kochi',
    '40': '福岡県 fukuoka',
    '41': '佐賀県 saga',
    '42': '長崎県 nagasaki',
    '43': '熊本県 kumamoto',
    '44': '大分県 oita',
    '45': '宮崎県 miyazaki',
    '46': '鹿児島県 kagoshima',
    '47': '沖縄県 okinawa',
}

LANGUAGE_LIST = {
    '1': '英語',
    '2': '韓国語',
    '3': '中国語',
    '4': 'アラビア語',
    '5': 'イタリア語',
    '6': 'インドネシア語',
    '7': 'ウクライナ語',
    '8': 'ウズベク語',
    '9': 'ウルドゥー語',
    '10': 'エストニア語',
    '11': 'オランダ語',
    '12': 'カザフ語',
    '13': 'カンボジア語',
    '14': 'ギリシャ語',
    '15': 'クロアチア語',
    '16': 'シンハラ語',
    '17': 'スペイン語',
    '18': 'タイ語',
    '19': 'タミール語',
    '20': 'ダリー語',
    '21': 'テトゥン語',
    '22': 'ディベヒ語',
    '23': 'ドイツ語',
    '24': 'トルコ語',
    '25': 'ネパール語',
    '26': 'ハンガリー語',
    '27': 'ヒンディー語',
    '28': 'フィリピノ語',
    '29': 'ベンガル語',
    '30': 'ベトナム語',
    '31': 'フランス語',
    '32': 'ポルトガル語',
    '33': 'マレー語',
    '34': 'ミャンマー語',
    '35': 'モンゴル語',
    '36': 'ラオス語',
    '37': 'ロシア語'
}
SPECIFIED_SKILLS = [
    '介護',
    'ビルクリーニング',
    '素形材産業',
    '産業機械製造業',
    '電気・電子情報関連産業',
    '建設',
    '造船・舶用工業',
    '自動車整備',
    '航空',
    '宿泊',
    '農業',
    '漁業',
    '飲食料品製造業',
    '外食業',
]

VISA_LIST = [
    '留学',
    '特定技能',
    '技能実習',
    '特定活動',
    '家族滞在',
    '研修',
    '就業',
    '永住',
    '高度専門職',
]
REQUIRED  = {
    '1': '有',
    '0': '無',
}
